# ===== Prepare source data for Figure 10 =====

library(data.table)

# -------------------------------------------------------------------------
# Locate repository root
# -------------------------------------------------------------------------

args <- commandArgs(trailingOnly = FALSE)
file_arg <- grep("^--file=", args, value = TRUE)

if (length(file_arg) == 1) {
  script_path <- sub("^--file=", "", file_arg)
  script_dir <- dirname(normalizePath(script_path))
  repo_root <- normalizePath(file.path(script_dir, ".."))
} else {
  repo_root <- normalizePath(".")
}

source_dir <- file.path(
  repo_root,
  "source_data",
  "figure_source_data",
  "Figure_10"
)

dir.create(source_dir, recursive = TRUE, showWarnings = FALSE)

# =========================================================================
# Figure 10A-C: revised multiple-testing-aware integration and SMR results
# =========================================================================
#
# Figure 10A:
#   - FAP DEGs are based on the revised primary pseudobulk framework:
#       * formal DE limited to donor-adequate cell types
#       * FAP1-FAP3 included in the FAP integration
#       * BH correction performed across tested genes within each cell type
#       * FDR < 0.05 used as the primary DEG criterion
#   - UKB SMR discovery uses cohort-wide BH correction across all tested
#     tissue-gene hypotheses together with HEIDI p > 0.01.
#   - FinnGen is not included as an independent discovery set in the UpSet
#     plot; it is used for targeted replication of UKB-carried hypotheses.
#
# Figure 10B:
#   - SMAD3 UKB SMR results display raw -log10(p_SMR) for visualization.
#   - Corrected discovery requires cohort-wide BH FDR < 0.05 and
#     HEIDI p > 0.01.
#
# Figure 10C:
#   - FinnGen is evaluated as targeted replication of hypotheses carried
#     forward from corrected UKB discovery.
#   - BH correction is applied across the carried-forward replication
#     hypotheses, with HEIDI p > 0.01 required.
#
# Figure 10A-C processed source resources are generated by:
#   scripts/06F_Regenerate_Figure10ABC.R
#
# This production workflow reconstructs the revised results directly from
# canonical pseudobulk, hdWGCNA, and combined SMR resources.

fig10_processed_dir <- file.path(
  repo_root,
  "processed_results",
  "06_SMR_HEIDI",
  "figure10"
)

required_fig10_files <- c(
  "Figure10A_Upset_source_data.csv",
  "Figure10A_discovery_candidate_details.csv",
  "Figure10B_UKB_SMAD3_source_data.csv",
  "Figure10C_FinnGen_SMAD3_source_data.csv",
  "Figure10_targeted_FinnGen_replication_primary.csv"
)

missing_fig10_files <- required_fig10_files[
  !file.exists(file.path(fig10_processed_dir, required_fig10_files))
]

if (length(missing_fig10_files) > 0) {
  stop(
    paste0(
      "Missing production Figure 10 source file(s): ",
      paste(missing_fig10_files, collapse = ", "),
      "\nRun scripts/06F_Regenerate_Figure10ABC.R first."
    )
  )
}

# =========================================================================
# Figure 10A: revised UpSet source data
# =========================================================================

fig10a <- fread(
  file.path(
    fig10_processed_dir,
    "Figure10A_Upset_source_data.csv"
  )
)

fig10a_candidates <- fread(
  file.path(
    fig10_processed_dir,
    "Figure10A_discovery_candidate_details.csv"
  )
)

fwrite(
  fig10a,
  file.path(
    source_dir,
    "Figure10A_Upset_source_data.csv"
  )
)

fwrite(
  fig10a_candidates,
  file.path(
    source_dir,
    "Figure10A_discovery_candidate_details.csv"
  )
)

# =========================================================================
# Figure 10B: corrected UKB SMAD3 SMR/HEIDI results
# =========================================================================

fig10b <- fread(
  file.path(
    fig10_processed_dir,
    "Figure10B_UKB_SMAD3_source_data.csv"
  )
)

fwrite(
  fig10b,
  file.path(
    source_dir,
    "Figure10B_UKB_SMAD3_source_data.csv"
  )
)

# =========================================================================
# Figure 10C: targeted FinnGen SMAD3 replication
# =========================================================================

fig10c <- fread(
  file.path(
    fig10_processed_dir,
    "Figure10C_FinnGen_SMAD3_source_data.csv"
  )
)

fig10_targeted_replication <- fread(
  file.path(
    fig10_processed_dir,
    "Figure10_targeted_FinnGen_replication_primary.csv"
  )
)

fwrite(
  fig10c,
  file.path(
    source_dir,
    "Figure10C_FinnGen_SMAD3_source_data.csv"
  )
)

fwrite(
  fig10_targeted_replication,
  file.path(
    source_dir,
    "Figure10_targeted_FinnGen_replication_source_data.csv"
  )
)

# =========================================================================
# Figure 10D: corrected GCTA-COJO independent signals
# =========================================================================

ukb_cojo <- fread(
  file.path(
    repo_root,
    "processed_results",
    "07_GCTA_COJO",
    "UKB_SMAD3_GCTA_corrected.jma.cojo"
  )
)
ukb_cojo[, study := "UKB"]

fin_cojo <- fread(
  file.path(
    repo_root,
    "processed_results",
    "07_GCTA_COJO",
    "Finn_SMAD3_GCTA_corrected.jma.cojo"
  )
)
fin_cojo[, study := "FinnGen"]

fig10d <- rbindlist(
  list(ukb_cojo, fin_cojo),
  use.names = TRUE,
  fill = TRUE
)

fig10d[, neg_log10_pJ := -log10(pJ)]

setcolorder(
  fig10d,
  c(
    "study",
    setdiff(names(fig10d), "study")
  )
)

fwrite(
  fig10d,
  file.path(source_dir, "Figure10D_GCTA_COJO_source_data.csv")
)

# =========================================================================
# Figure 10E: standard COLOC results for SMAD3
# =========================================================================

coloc <- fread(
  file.path(
    repo_root,
    "processed_results",
    "08_colocalization",
    "COLOC_all_studies_PPH4_gt_0p75.csv"
  )
)

fig10e <- coloc[gene == "SMAD3"]

fwrite(
  fig10e,
  file.path(source_dir, "Figure10E_COLOC_source_data.csv")
)

# =========================================================================
# Summary
# =========================================================================

cat("Figure 10 source-data directory:", source_dir, "\n")
cat("Figure 10A rows:", nrow(fig10a), "\n")
cat("Figure 10A candidate-detail rows:", nrow(fig10a_candidates), "\n")
cat("Figure 10B rows:", nrow(fig10b), "\n")
cat("Figure 10C rows:", nrow(fig10c), "\n")
cat("Figure 10 targeted-replication rows:", nrow(fig10_targeted_replication), "\n")
cat("Figure 10D rows:", nrow(fig10d), "\n")
cat("Figure 10E rows:", nrow(fig10e), "\n")
